### PR TITLE
Issue 141

### PR DESCRIPTION
**Pull request by ferrighi**
This should cover the inclusion of the eo elements which belongs to acquisitionInformation, i.e. platform, instrument and cloud coverage. It also includes a fix of the mmdv2-to-mmv3 to pick up the cloud coverage correctly. Please @epifanio use these 2 files to test transformation and indexing in csw. If it looks good we can merge.

### CODE REVIEW

**Comment by ferrighi** [comment]
converting to draft since we are adding few more elements

**Review by epifanio — APPROVED** [review]

**Review by epifanio — APPROVED** [review]
looks good - shall we run some test on the demo endpoint?

**Comment by ferrighi** [comment]
Yes I think it will be good if you can run the mmd-to-iso2 on a bunch of xml and index them

**Comment by mortenwh** [comment]
I see there is a new file `mmd-to-iso2.xsl` now? Is that replacing `mmd-to-iso.xsl`? py-mmd-tools uses `mmd-to-iso.xsl` - it is very important that this is handled correctly...

**Review by mortenwh — CHANGES_REQUESTED** [review]
See comment above

**Comment by ferrighi** [comment]
mmd-to-iso.xsl translates to iso19115, mmd-to-iso2.xsl translates to iso19115-2, i.e. including the acquisition information (gmi:acquisitionInformation). I think we need to have both as they might be used for different purposes.

**Comment by mortenwh** [comment]
ok - can we rename them to `mmd-to-iso19115.xsl` and `mmd-to-iso19115-2` (or even iso19139)? Or/and can it be specified as comments inside the files?

**Comment by mortenwh** [comment]
anyway - the most important is to know which xslt we should use in the iso-converter container that translates from MMD to the ISO files used in pycsw :)

**Comment by ferrighi** [comment]
Sure, that has to be chosen depending on the pycsw endpoint. For s-enda it will then be mmd-to-inspire.xsl if you want to expose the iso inspire profile.

**Comment by ferrighi** [comment]
@mortenwh do you think we can merge this?

**Review by mortenwh — APPROVED** [review]
It looks good but I still think the naming could be more explicit and/or there could be a comment inside the files to explain what they are for. I suggest you decide what to do :)

**Comment by ferrighi** [comment]
Sorry you are right, I said I was going to do that. I have added a comment in the files.

**Pull request merged**
