### PR TITLE
Issue185 invalid attributes

### PR DESCRIPTION
**Pull request by mortenwh**
@ferrighi - can you have a look? I'm not sure if we need to do anything in mmd.xsd as well. I guess we should, but there seems to be other issues as well. And should we also test other attributes?

### CODE REVIEW

**Comment by ferrighi** [comment]
I have some comments:
- there is another attribute that crucial for translation to geonorge profile, which is the xml:lang for title and abstract. 
- currently none of the attributes (srsName and xml:lang) are mandatory. 
- this can be fixed either by making them mandatory in the mmd_strict.xsd or by handling missing values in the mmd-to-geonorge xslt (this is how we do it for ADC), assuming default values 'en' and 'EPSG:4326'. 
-- In the first case (what you are doing with the PR), I think you should not just check for the non-empty string, because if the attribute srsName is missing it will validate anyway. But you should make the attribute mandatory (<xs:attribute name="srsName" use="required">). 
-- In the second case we just need to change the mmd-to-geonorge.xslt (I can do that).

**Comment by mortenwh** [comment]
Thanks - tried to implement required for xml:lang as well but it doesn't seem to work. Could you have a look?

**Comment by ferrighi** [comment]
For the srsName you need, both the attribute to be required and non empty:

        <xs:attribute name="srsName" use="required">
           <xs:simpleType>
              <xs:restriction base="xs:string">
                 <xs:minLength value="1"/>
              </xs:restriction>
           </xs:simpleType>
       </xs:attribute>

For the xml:lang, unfortunately I think you can only have it required, but you can't force the non empty string. This is because the xml:lang is defined by the xml schama (https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#language) externally and the empty string is a valid entry. So I think we'll need to modify the mmd-to-geonorge.xslt in order to cover for a potential empty string. We'll then assume the strings are in English.

For the test, I think you need to push the precipitation_amount_st_92350_NO_LANG_ATTR.xml file

**Comment by mortenwh** [comment]
Thanks - it seems to work now, also for the missing xml:lang attribute :) So this is now only implemented in `mmd_strict.xsd` - should we also have it in `mmd.xsd`?

**Pull request merged**
