### PR TITLE
add dateutil and validators to Dockerfile

### PR DESCRIPTION
**Pull request by ferrighi**

### CODE REVIEW

**Comment by mortenwh** [comment]
why is this needed?

**Comment by ferrighi** [comment]
I see that the last commit didn't pass the test. There are some changes in the nc_to_mmd importing new modules, so I tried to fix them.

**Comment by mortenwh** [comment]
But this PR is only for the dockerfile? I learned from Veronica that we should be careful with using too many libraries. Do you think it would be possible to avoid any of them?

**Comment by mortenwh** [comment]
aha - so nc_to_mmd in the py-mmd-tools package? Then, the change should be there shouldn't it? Maybe we need to talk....

**Review by mortenwh — APPROVED** [review]

**Pull request merged**
