### PR TITLE
add type to related_information

### PR DESCRIPTION
**Pull request by ferrighi**
An extended list of related_information type is added to support links to publications in forms of scientific publications, data paper, text, software. The type are inspired by DataCite resourcetype and could be extended. The resource is specified to be the landing page of the publication, and not a file.

### CODE REVIEW

**Review by mortenwh — COMMENTED** [review]
It looks good. I'm only wondering:

- isn't a data paper also a publication? Is that type needed?

- should we also have XML examples for data paper, text, and software?

- preferably, the resources should also have DOIs and version information but that would be out of our control and therefore only restrictive, right? I.e., we want to keep it open, like it is now..?

**Comment by ferrighi** [comment]
1) To my understanding a data paper is surely a publication, but a data paper has the primary scope to to describe a dataset or a dataset collection, rather than addressing any scientific research investigation. It's just a human-readable version of the data in a way. That is why I think it's nice to have that type highlighted. 
2) Since they are all the same I don't think it matters. 
3) the resource is the landing page of the publication and it can (or maybe even should) be a DOI, but it is not mandatory. For examples if you have a conference poster, you probably don't have/need a DOI. Maybe the free text "description" could be used to add the full citation info.

**Comment by mortenwh** [comment]
>     1. To my understanding a data paper is surely a publication, but a data paper has the primary scope to to describe a dataset or a dataset collection, rather than addressing any scientific research investigation. It's just a human-readable version of the data in a way. That is why I think it's nice to have that type highlighted.

Ok. I'm a bit skeptical. You could have several publications, right? Maybe it is enough to have the more general term "publication" only.

> 
>     2. Since they are all the same I don't think it matters.

I agree

> 
>     3. the resource is the landing page of the publication and it can (or maybe even should) be a DOI, but it is not mandatory. For examples if you have a conference poster, you probably don't have/need a DOI. Maybe the free text "description" could be used to add the full citation info.

Ok, so "description" should be added? But why not adding (not mandatory) fields like the following (see list at https://www.easybib.com/guides/citation-guides/how-do-i-cite-a/how-to-cite-a-powerpoint-presentation/)?

-    Author or authors of the resource
-    Resource title
-    Date of publication/presentation
-    Place of publication/where the presentation was given
-    URI (if used to locate the presentation)

**Comment by ferrighi** [comment]
Yes, repetition is allowed, so you can have a data paper (describing data) and a scientific publication (using/citing data). If we want to just be general it's ok to have one type. But it can be useful to be able to identify easily the data paper I think. The "description" element is already included in mmd, so we don't need to add it. 

I would not add citation elements for the publication here as mmd is collecting metadata for the dataset and it is not used for describing papers relating to it. Citation elements of the publications belong to the publication itself and can be reached through the landing page of the paper.

**Comment by mortenwh** [comment]
> Yes, repetition is allowed, so you can have a data paper (describing data) and a scientific publication (using/citing data). If we want to just be general it's ok to have one type. But it can be useful to be able to identify easily the data paper I think. The "description" element is already included in mmd, so we don't need to add it.

Ok, that sounds good :)

> 
> I would not add citation elements for the publication here as mmd is collecting metadata for the dataset and it is not used for describing papers relating to it. Citation elements of the publications belong to the publication itself and can be reached through the landing page of the paper.

I see - and the URI is mandatory, then?

**Comment by ferrighi** [comment]
From the actual schema it isn't actually, but if the element is used then it should be. I'll push that change.

**Comment by mortenwh** [comment]
👍

tir. 6. okt. 2020, 17:52 skrev Lara Ferrighi <notifications@github.com>:

**Comment by steingod** [comment]
I think it is good to separate between a data paper and a scientific publication as the former is actually "extended metadata" for the dataset. It is not just a human readable form of the data, but also includes further information on decisions taken when preparing or collecting the data. As such I think this is good, but I am not comfortable with the keyword Text where I think the description is better than the keyword. I would prefer something along "Other documentation" and certainly to separate Data Management Plan from this. DMPs are getting more and more important and should be a separate choice.

**Comment by ferrighi** [comment]
I agree with this. "Text" is used in DataCite, but it indeed rather vague. I have added, Scientific publication, Data paper, DMP and Other documents. @mortenwh you can check and merge if it is ok.

**Review by steingod — APPROVED** [review]
Looks good to me.

**Review by mortenwh — APPROVED** [review]

**Comment by mortenwh** [comment]
btw - was this connected to an issue?

**Comment by ferrighi** [comment]
Yes, Link publications to datasets. It is closed now.

**Pull request merged**
